### ISSUE TITLE
Unable to build wheel of project with Cython extension code

### ISSUE THREAD

**Issue by manselmi** [pypa/build#148]
Hi there!  First, thank you for your work on the Python packaging ecosystem.  It's much appreciated!  Now to my issue:

Using `python -m pep517.build -b …` I have for a while now been successfully building wheels of a project with a Cython extension code.  However, I am unable to build a wheel if I run `python -m build -w …`.

I have a stripped down version of the project here: https://github.com/manselmi/pypa-build-debug

Steps to reproduce:

1. Clone the above repo and change to top-level directory of the repo.
2. Pull the `quay.io/pypa/manylinux2014_x86_64:latest` Docker image and start a container with the current directory mounted to the current directory of the container:

   ```
   IMAGE=quay.io/pypa/manylinux2014_x86_64:latest
   docker image pull -- "${IMAGE}"
   docker container run \
     --interactive \
     --tty \
     --rm \
     --mount type=bind,source="$(pwd)",target=/mnt/workspace \
     --workdir /mnt/workspace \
     -- \
     "${IMAGE}"
   ```

3. Attempt to build a wheel via `python -m build -w …`:

   ```
   PYTHON=/opt/python/cp39-cp39/bin/python
   "${PYTHON}" -m pip install --upgrade -- pip setuptools wheel
   "${PYTHON}" -m pip install -- build pep517
   "${PYTHON}" -m pip list --format=freeze
   # build==0.0.4
   # packaging==20.4
   # pep517==0.9.1
   # pip==20.2.4
   # pyparsing==2.4.7
   # setuptools==50.3.2
   # six==1.15.0
   # toml==0.10.1
   # wheel==0.35.1

   "${PYTHON}" -m build -w -o wheelhouse -- .
   ```

Expected result: a wheel is successfully created.

Actual result:

```
"${PYTHON}" -m build -w -o wheelhouse -- .
# Looking in links: /tmp/tmp0e12z5rn
# Processing /tmp/tmp0e12z5rn/setuptools-49.2.1-py3-none-any.whl
# Processing /tmp/tmp0e12z5rn/pip-20.2.3-py2.py3-none-any.whl
# Installing collected packages: setuptools, pip
# Successfully installed pip setuptools
# Requirement already satisfied: setuptools in /tmp/build-env-6ycr3hzw/lib/python3.9/site-packages (from -r /tmp/build-reqs-04woj82s.txt (line 1)) (49.2.1)
# Collecting setuptools-scm[toml]
#   Downloading setuptools_scm-4.1.2-py2.py3-none-any.whl (27 kB)
# Collecting wheel
#   Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
# Collecting Cython
#   Downloading Cython-0.29.21-cp39-cp39-manylinux1_x86_64.whl (1.9 MB)
#      |████████████████████████████████| 1.9 MB 3.0 MB/s
# Collecting toml; extra == "toml"
#   Using cached toml-0.10.1-py2.py3-none-any.whl (19 kB)
# Installing collected packages: toml, setuptools-scm, wheel, Cython
# Successfully installed Cython-0.29.21 setuptools-scm-4.1.2 toml-0.10.1 wheel-0.35.1
# WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
# You should consider upgrading via the '/opt/python/cp39-cp39/bin/python -m pip install --upgrade pip' command.
# Compiling src/pypa_build_debug/_primes.pyx because it changed.
# [1/1] Cythonizing src/pypa_build_debug/_primes.pyx
# running bdist_wheel
# running build
# running build_py
# creating build
# creating build/lib.linux-x86_64-3.9
# creating build/lib.linux-x86_64-3.9/pypa_build_debug
# copying src/pypa_build_debug/__init__.py -> build/lib.linux-x86_64-3.9/pypa_build_debug
# copying src/pypa_build_debug/_version.py -> build/lib.linux-x86_64-3.9/pypa_build_debug
# running egg_info
# creating src/pypa_build_debug.egg-info
# writing src/pypa_build_debug.egg-info/PKG-INFO
# writing dependency_links to src/pypa_build_debug.egg-info/dependency_links.txt
# writing top-level names to src/pypa_build_debug.egg-info/top_level.txt
# writing manifest file 'src/pypa_build_debug.egg-info/SOURCES.txt'
# reading manifest template 'MANIFEST.in'
# writing manifest file 'src/pypa_build_debug.egg-info/SOURCES.txt'
# copying src/pypa_build_debug/__init__.pyi -> build/lib.linux-x86_64-3.9/pypa_build_debug
# copying src/pypa_build_debug/_primes.pyx -> build/lib.linux-x86_64-3.9/pypa_build_debug
# copying src/pypa_build_debug/_version.pyi -> build/lib.linux-x86_64-3.9/pypa_build_debug
# copying src/pypa_build_debug/py.typed -> build/lib.linux-x86_64-3.9/pypa_build_debug
# running build_ext
# building 'pypa_build_debug._primes' extension
# creating build/temp.linux-x86_64-3.9
# creating build/temp.linux-x86_64-3.9/src
# creating build/temp.linux-x86_64-3.9/src/pypa_build_debug
# gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/build-env-6ycr3hzw/include/python3.9 -c src/pypa_build_debug/_primes.cpp -o build/temp.linux-x86_64-3.9/src/pypa_build_debug/_primes.o
# src/pypa_build_debug/_primes.cpp:18:10: fatal error: Python.h: No such file or directory
#    18 | #include "Python.h"
#       |          ^~~~~~~~~~
# compilation terminated.
# error: command '/opt/rh/devtoolset-9/root/usr/bin/gcc' failed with exit code 1
# Traceback (most recent call last):
#   File "/opt/python/cp39-cp39/lib/python3.9/subprocess.py", line 373, in check_call
#     raise CalledProcessError(retcode, cmd)
# subprocess.CalledProcessError: Command '['/opt/python/cp39-cp39/bin/python', '/opt/python/cp39-cp39/lib/python3.9/site-packages/pep517/_in_process.py', 'build_wheel', '/tmp/tmp5rgo130g']' returned non-zero exit status 1.
# 
# During handling of the above exception, another exception occurred:
# 
# Traceback (most recent call last):
#   File "/opt/python/cp39-cp39/lib/python3.9/site-packages/build/__init__.py", line 215, in build
#     raise BuildBackendException('Backend operation failed: {}'.format(e))
# build.BuildBackendException: Backend operation failed: Command '['/opt/python/cp39-cp39/bin/python', '/opt/python/cp39-cp39/lib/python3.9/site-packages/pep517/_in_process.py', 'build_wheel', '/tmp/tmp5rgo130g']' returned non-zero exit status 1.
# 
# ERROR Backend operation failed: Command '['/opt/python/cp39-cp39/bin/python', '/opt/python/cp39-cp39/lib/python3.9/site-packages/pep517/_in_process.py', 'build_wheel', '/tmp/tmp5rgo130g']' returned non-zero exit status 1.
```

Please note that this works fine when using `pep517.build` directly:

```
"${PYTHON}" -m pep517.build -b -o wheelhouse -- .
# Compiling src/pypa_build_debug/_primes.pyx because it changed.
# [1/1] Cythonizing src/pypa_build_debug/_primes.pyx
# running egg_info
# creating src/pypa_build_debug.egg-info
# writing src/pypa_build_debug.egg-info/PKG-INFO
# writing dependency_links to src/pypa_build_debug.egg-info/dependency_links.txt
# writing top-level names to src/pypa_build_debug.egg-info/top_level.txt
# writing manifest file 'src/pypa_build_debug.egg-info/SOURCES.txt'
# reading manifest template 'MANIFEST.in'
# writing manifest file 'src/pypa_build_debug.egg-info/SOURCES.txt'
# running bdist_wheel
# running build
# running build_py
# creating build
# creating build/lib.linux-x86_64-3.9
# creating build/lib.linux-x86_64-3.9/pypa_build_debug
# copying src/pypa_build_debug/__init__.py -> build/lib.linux-x86_64-3.9/pypa_build_debug
# copying src/pypa_build_debug/_version.py -> build/lib.linux-x86_64-3.9/pypa_build_debug
# running egg_info
# writing src/pypa_build_debug.egg-info/PKG-INFO
# writing dependency_links to src/pypa_build_debug.egg-info/dependency_links.txt
# writing top-level names to src/pypa_build_debug.egg-info/top_level.txt
# reading manifest template 'MANIFEST.in'
# writing manifest file 'src/pypa_build_debug.egg-info/SOURCES.txt'
# copying src/pypa_build_debug/__init__.pyi -> build/lib.linux-x86_64-3.9/pypa_build_debug
# copying src/pypa_build_debug/_primes.pyx -> build/lib.linux-x86_64-3.9/pypa_build_debug
# copying src/pypa_build_debug/_version.pyi -> build/lib.linux-x86_64-3.9/pypa_build_debug
# copying src/pypa_build_debug/py.typed -> build/lib.linux-x86_64-3.9/pypa_build_debug
# running build_ext
# building 'pypa_build_debug._primes' extension
# creating build/temp.linux-x86_64-3.9
# creating build/temp.linux-x86_64-3.9/src
# creating build/temp.linux-x86_64-3.9/src/pypa_build_debug
# gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/opt/python/cp39-cp39/include/python3.9 -c src/pypa_build_debug/_primes.cpp -o build/temp.linux-x86_64-3.9/src/pypa_build_debug/_primes.o
# g++ -pthread -shared build/temp.linux-x86_64-3.9/src/pypa_build_debug/_primes.o -o build/lib.linux-x86_64-3.9/pypa_build_debug/_primes.cpython-39-x86_64-linux-gnu.so
# installing to build/bdist.linux-x86_64/wheel
# running install
# running install_lib
# creating build/bdist.linux-x86_64
# creating build/bdist.linux-x86_64/wheel
# creating build/bdist.linux-x86_64/wheel/pypa_build_debug
# copying build/lib.linux-x86_64-3.9/pypa_build_debug/__init__.py -> build/bdist.linux-x86_64/wheel/pypa_build_debug
# copying build/lib.linux-x86_64-3.9/pypa_build_debug/__init__.pyi -> build/bdist.linux-x86_64/wheel/pypa_build_debug
# copying build/lib.linux-x86_64-3.9/pypa_build_debug/_primes.cpython-39-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/pypa_build_debug
# copying build/lib.linux-x86_64-3.9/pypa_build_debug/_primes.pyx -> build/bdist.linux-x86_64/wheel/pypa_build_debug
# copying build/lib.linux-x86_64-3.9/pypa_build_debug/_version.py -> build/bdist.linux-x86_64/wheel/pypa_build_debug
# copying build/lib.linux-x86_64-3.9/pypa_build_debug/_version.pyi -> build/bdist.linux-x86_64/wheel/pypa_build_debug
# copying build/lib.linux-x86_64-3.9/pypa_build_debug/py.typed -> build/bdist.linux-x86_64/wheel/pypa_build_debug
# running install_egg_info
# Copying src/pypa_build_debug.egg-info to build/bdist.linux-x86_64/wheel/pypa_build_debug-0.1.dev1+g47459a9-py3.9.egg-info
# running install_scripts
# creating build/bdist.linux-x86_64/wheel/pypa_build_debug-0.1.dev1+g47459a9.dist-info/WHEEL
# creating '/tmp/tmplk59b1d9/tmp2oqk84zi/pypa_build_debug-0.1.dev1+g47459a9-cp39-cp39-linux_x86_64.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
# adding 'pypa_build_debug/__init__.py'
# adding 'pypa_build_debug/__init__.pyi'
# adding 'pypa_build_debug/_primes.cpython-39-x86_64-linux-gnu.so'
# adding 'pypa_build_debug/_primes.pyx'
# adding 'pypa_build_debug/_version.py'
# adding 'pypa_build_debug/_version.pyi'
# adding 'pypa_build_debug/py.typed'
# adding 'pypa_build_debug-0.1.dev1+g47459a9.dist-info/METADATA'
# adding 'pypa_build_debug-0.1.dev1+g47459a9.dist-info/WHEEL'
# adding 'pypa_build_debug-0.1.dev1+g47459a9.dist-info/top_level.txt'
# adding 'pypa_build_debug-0.1.dev1+g47459a9.dist-info/RECORD'
# removing build/bdist.linux-x86_64/wheel
```

I've noticed the calls to `gcc` differ.  When using `python -m build` we have

```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/build-env-6ycr3hzw/include/python3.9 -c src/pypa_build_debug/_primes.cpp -o build/temp.linux-x86_64-3.9/src/pypa_build_debug/_primes.o
```

and `python -m pep517.build` we have

```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/opt/python/cp39-cp39/include/python3.9 -c src/pypa_build_debug/_primes.cpp -o build/temp.linux-x86_64-3.9/src/pypa_build_debug/_primes.o
```

The only difference is an include directory: the former references an include directory within the isolated build environment, while the latter references the include directory of the base Python environment.

I would like to switch from `python -m pep517.build` to `python -m build` since the former is deprecated, but this issue prevents me from doing so.

Thanks for your consideration.

**Comment by FFY00** [comment]
Hi @manselmi, sorry for your troubles. This has been potentially already fixed in master because we moved the isolation environment creation to venv. Would you mind to try?

**Comment by manselmi** [comment]
Hi @FFY00, thanks for the suggestion.  I should have thought of that myself!  👉👈

Interestingly, that also doesn't work for me.  I repeated the above instructions with the exception of cloning the `pypa/build` repo, building a wheel from commit 784f8cf1a883d3bbbbe5cdf8cef1b5bcfb832130 (current tip of `master`) via `python -m pep517.build -b …`, and then installing `build` via that wheel instead of from PyPI.  Here's the end result:

```
"${PYTHON}" -m build -w -o wheelhouse -- .
# Collecting Cython
#   Downloading Cython-0.29.21-cp39-cp39-manylinux1_x86_64.whl (1.9 MB)
#      |████████████████████████████████| 1.9 MB 2.0 MB/s
# Collecting setuptools
#   Using cached setuptools-50.3.2-py3-none-any.whl (785 kB)
# Collecting setuptools-scm[toml]
#   Downloading setuptools_scm-4.1.2-py2.py3-none-any.whl (27 kB)
# Collecting wheel
#   Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
# Collecting toml; extra == "toml"
#   Using cached toml-0.10.1-py2.py3-none-any.whl (19 kB)
# Installing collected packages: Cython, setuptools, toml, setuptools-scm, wheel
# Successfully installed Cython-0.29.21 setuptools-50.3.2 setuptools-scm-4.1.2 toml-0.10.1 wheel-0.35.1
# Traceback (most recent call last):
#   File "/opt/python/cp39-cp39/lib/python3.9/site-packages/pep517/_in_process.py", line 280, in <module>
#     main()
#   File "/opt/python/cp39-cp39/lib/python3.9/site-packages/pep517/_in_process.py", line 263, in main
#     json_out['return_val'] = hook(**hook_input['kwargs'])
#   File "/opt/python/cp39-cp39/lib/python3.9/site-packages/pep517/_in_process.py", line 204, in build_wheel
#     return _build_backend().build_wheel(wheel_directory, config_settings,
#   File "/opt/python/cp39-cp39/lib/python3.9/site-packages/setuptools/build_meta.py", line 216, in build_wheel
#     return self._build_with_temp_dir(['bdist_wheel'], '.whl',
#   File "/opt/python/cp39-cp39/lib/python3.9/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
#     self.run_setup()
#   File "/opt/python/cp39-cp39/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
#     exec(compile(code, __file__, 'exec'), locals())
#   File "setup.py", line 5, in <module>
#     import Cython.Build
# ModuleNotFoundError: No module named 'Cython'
# Traceback (most recent call last):
#   File "/opt/python/cp39-cp39/lib/python3.9/subprocess.py", line 373, in check_call
#     raise CalledProcessError(retcode, cmd)
# subprocess.CalledProcessError: Command '['/opt/python/cp39-cp39/bin/python', '/opt/python/cp39-cp39/lib/python3.9/site-packages/pep517/_in_process.py', 'build_wheel',
# '/tmp/tmpamlqxk6l']' returned non-zero exit status 1.
# 
# During handling of the above exception, another exception occurred:
# 
# Traceback (most recent call last):
#   File "/opt/python/cp39-cp39/lib/python3.9/site-packages/build/__init__.py", line 209, in build
#     raise BuildBackendException('Backend operation failed: {!r}'.format(e))
# build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['/opt/python/cp39-cp39/bin/python', '/opt/python/cp39-cp39/lib/python3.9/site-packages/pep517/_in_process.py', 'build_wheel', '/tmp/tmpamlqxk6l'])
# 
# ERROR Backend operation failed: CalledProcessError(1, ['/opt/python/cp39-cp39/bin/python', '/opt/python/cp39-cp39/lib/python3.9/site-packages/pep517/_in_process.py', 'build_wheel', '/tmp/tmpamlqxk6l'])
```

`ModuleNotFoundError: No module named 'Cython'` is quite the surprise!  😳

**Comment by FFY00** [comment]
It seems this got broken somewhere in our refactoring, which is still undergoing. We were previously monkey patching `sys.executable` to be able the build in the custom environment, due to https://github.com/pypa/pep517/issues/92, but `pep517` 0.9 got released yesterday with proper support for it so we can now fix it properly :blush: I think #149 should fix it for you, please give it a try.

**Comment by manselmi** [comment]
@FFY00 https://github.com/pypa/build/pull/149 resolves my issue.  Thank you so much!  🥳

**Comment by FFY00** [comment]
We just released! This should now be fixed, can you check?

**Comment by manselmi** [comment]
@FFY00 Yes, I’m all set with the latest release. Thanks!
