### ISSUE TITLE
failure when `ensurepip` is missing

### ISSUE THREAD

**Issue by asottile** [pypa/build#173]
this is a common situation on debianlike platforms where the ensurepip module is stripped (unless `pythonX.X-venv` is installed)

```console
$ python -m build
/tmp/ldaptor/venv/bin/python: No module named ensurepip
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ldaptor/venv/lib/python3.8/site-packages/build/__main__.py", line 176, in <module>
    main(sys.argv[1:], 'python -m build')
  File "/tmp/ldaptor/venv/lib/python3.8/site-packages/build/__main__.py", line 168, in main
    build(args.srcdir, args.outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "/tmp/ldaptor/venv/lib/python3.8/site-packages/build/__main__.py", line 80, in build
    _build_in_isolated_env(builder, outdir, distributions)
  File "/tmp/ldaptor/venv/lib/python3.8/site-packages/build/__main__.py", line 45, in _build_in_isolated_env
    env.install(builder.build_dependencies)
  File "/tmp/ldaptor/venv/lib/python3.8/site-packages/build/env.py", line 167, in install
    subprocess.check_call([sys.executable, '-m', 'ensurepip'], cwd=self.path)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/ldaptor/venv/bin/python', '-m', 'ensurepip']' returned non-zero exit status 1.
```

**Comment by gaborbernat** [comment]
This is fixed now on the master. As long as the ``python`` environment has pip we'll use that instead of delegating it to ensurepip. In case neither python has a pip (``/tmp/ldaptor/venv/bin/python`` in your case) and it does not have the `ensurepip` either, we'll still fail.

**Comment by gaborbernat** [comment]
Fixed via https://github.com/pypa/build/pull/140.

**Comment by FFY00** [comment]
See #106, and https://github.com/pypa/build/blob/9504fc5227a01e5893e3e5c5fb0b0b3d9e7ded1f/src/build/env.py#L162.

You either need pip installed or a working venv.

**Comment by gaborbernat** [comment]
> You either need pip installed or a working venv package.

This is only true once we release the master.

**Comment by gaborbernat** [comment]
Just to clarify: you always need a working venv package on python 3 (on python 2 we use virtualenv as a dependency). If your host pip has pip installed you're good to go, if not you need ensurepip package from stdlib working.
