### ISSUE TITLE
pytest sometimes throws `ConftestImportFailure` with pytest-xdist (multiprocessing) on macOS when testing wheel builds

### ISSUE THREAD

**Issue by layday** [pypa/build#186]
```
$ tox -e py39-wheel
.package create: /Users/layday/code/build/.tox/.package
.package installdeps: setuptools >= 40.8.0, wheel
py39-wheel create: /Users/layday/code/build/.tox/py39-wheel
py39-wheel installdeps: -rrequirements-dev.txt
py39-wheel inst: /Users/layday/code/build/.tox/.tmp/package/1/build-0.1.0.tar.gz
py39-wheel installed: apipkg==1.5,attrs==20.3.0,build @ file:///Users/layday/code/build/.tox/.tmp/package/1/build-0.1.0.tar.gz,coverage==5.3,execnet==1.7.1,filelock==3.0.12,iniconfig==1.1.1,packaging==20.4,pep517==0.9.1,pluggy==0.13.1,py==1.9.0,pyparsing==2.4.7,pytest==6.1.2,pytest-cov==2.10.1,pytest-forked==1.3.0,pytest-mock==3.3.1,pytest-xdist==2.1.0,six==1.15.0,toml==0.10.2
py39-wheel run-test-pre: PYTHONHASHSEED='735881058'
py39-wheel run-test: commands[0] | pytest -rsx --cov --cov-config setup.cfg --cov-report=html:/Users/layday/code/build/.tox/py39-wheel/htmlcov --cov-context=test --cov-report=xml:/Users/layday/code/build/.tox/coverage.py39-wheel.xml tests -n auto
================================================= test session starts =================================================
platform darwin -- Python 3.9.0, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
cachedir: .tox/py39-wheel/.pytest_cache
rootdir: /Users/layday/code/build, configfile: setup.cfg
plugins: xdist-2.1.0, mock-3.3.1, cov-2.10.1, forked-1.3.0
gw0 C / gw1 C / gw2 C / gw3 Cerror: [Errno 2] No such file or directory: 'build/bdist.macosx-10.6-x86_64/wheel/build-0.1.0-py3.9.egg-info'
[gw1] node down: Traceback (most recent call last):
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 570, in _importconftest
    mod = import_path(conftestpath, mode=importmode)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/pathlib.py", line 517, in import_path
    importlib.import_module(module_name)
  File "/nix/store/qd9a9m03k6d4j3fvrflfynzn0yq7sdcg-python3-3.9.0/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 171, in exec_module
    exec(co, module.__dict__)
  File "/Users/layday/code/build/tests/conftest.py", line 35, in <module>
    _setup()
  File "/Users/layday/code/build/tests/conftest.py", line 28, in _setup
    subprocess.check_output(cmd, env=env)
  File "/nix/store/qd9a9m03k6d4j3fvrflfynzn0yq7sdcg-python3-3.9.0/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/qd9a9m03k6d4j3fvrflfynzn0yq7sdcg-python3-3.9.0/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/layday/code/build/.tox/py39-wheel/bin/python', '-m', 'build', '--wheel', '--no-isolation', '--outdir', '/tmp/tmph3yrfgek']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/xdist/remote.py", line 227, in <module>
    config = _prepareconfig(args, None)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config = outcome.get_result()  # type: Config
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1280, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1186, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1070, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(early_config.known_args_namespace)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 500, in _set_initial_conftests
    self._try_load_conftest(anchor, namespace.importmode)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 508, in _try_load_conftest
    self._getconftestmodules(anchor, importmode)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 536, in _getconftestmodules
    mod = self._importconftest(conftestpath, importmode)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 574, in _importconftest
    raise ConftestImportFailure(conftestpath, exc_info) from e
_pytest.config.ConftestImportFailure: CalledProcessError: Command '['/Users/layday/code/build/.tox/py39-wheel/bin/python', '-m', 'build', '--wheel', '--no-isolation', '--outdir', '/tmp/tmph3yrfgek']' returned non-zero exit status 1. (from /Users/layday/code/build/tests/conftest.py)


replacing crashed worker gw1
gw0 C / gw4 C / gw2 C / gw3 CTraceback (most recent call last):
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pep517/_in_process.py", line 280, in <module>
    main()
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pep517/_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pep517/_in_process.py", line 204, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/setuptools/build_meta.py", line 216, in build_wheel
    return self._build_with_temp_dir(['bdist_wheel'], '.whl',
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
    self.run_setup()
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 4, in <module>
    setup()
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/qd9a9m03k6d4j3fvrflfynzn0yq7sdcg-python3-3.9.0/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nix/store/qd9a9m03k6d4j3fvrflfynzn0yq7sdcg-python3-3.9.0/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/nix/store/qd9a9m03k6d4j3fvrflfynzn0yq7sdcg-python3-3.9.0/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 342, in run
    self.egg2dist(self.egginfo_dir, distinfo_dir)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 445, in egg2dist
    raise ValueError(err)
ValueError: Egg metadata expected at build/bdist.macosx-10.6-x86_64/wheel/build-0.1.0-py3.9.egg-info but not found
[gw3] node down: Traceback (most recent call last):
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 570, in _importconftest
    mod = import_path(conftestpath, mode=importmode)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/pathlib.py", line 517, in import_path
    importlib.import_module(module_name)
  File "/nix/store/qd9a9m03k6d4j3fvrflfynzn0yq7sdcg-python3-3.9.0/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 171, in exec_module
    exec(co, module.__dict__)
  File "/Users/layday/code/build/tests/conftest.py", line 35, in <module>
    _setup()
  File "/Users/layday/code/build/tests/conftest.py", line 28, in _setup
    subprocess.check_output(cmd, env=env)
  File "/nix/store/qd9a9m03k6d4j3fvrflfynzn0yq7sdcg-python3-3.9.0/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/qd9a9m03k6d4j3fvrflfynzn0yq7sdcg-python3-3.9.0/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/layday/code/build/.tox/py39-wheel/bin/python', '-m', 'build', '--wheel', '--no-isolation', '--outdir', '/tmp/tmpu64dcw8m']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/xdist/remote.py", line 227, in <module>
    config = _prepareconfig(args, None)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config = outcome.get_result()  # type: Config
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1280, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1186, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1070, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(early_config.known_args_namespace)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 500, in _set_initial_conftests
    self._try_load_conftest(anchor, namespace.importmode)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 508, in _try_load_conftest
    self._getconftestmodules(anchor, importmode)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 536, in _getconftestmodules
    mod = self._importconftest(conftestpath, importmode)
  File "/Users/layday/code/build/.tox/py39-wheel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 574, in _importconftest
    raise ConftestImportFailure(conftestpath, exc_info) from e
_pytest.config.ConftestImportFailure: CalledProcessError: Command '['/Users/layday/code/build/.tox/py39-wheel/bin/python', '-m', 'build', '--wheel', '--no-isolation', '--outdir', '/tmp/tmpu64dcw8m']' returned non-zero exit status 1. (from /Users/layday/code/build/tests/conftest.py)


replacing crashed worker gw3
gw0 [94] / gw4 [94] / gw2 [94] / gw5 [94]
.....................................................s.sss.sssssssssssssss.sssssssssss.s......                  [100%]

---------- coverage: platform darwin, python 3.9.0-final-0 -----------
---------------------- coverage: failed workers ----------------------
The following workers failed to return coverage data, ensure that pytest-cov is installed on these workers.
gw1
gw3
Coverage HTML written to dir /Users/layday/code/build/.tox/py39-wheel/htmlcov
Coverage XML written to file /Users/layday/code/build/.tox/coverage.py39-wheel.xml

=============================================== short test summary info ===============================================
SKIPPED [30] tests/test_integration.py:75: integration tests not run (no --run-integration flag)
SKIPPED [1] tests/test_integration.py: integration tests not run (no --run-integration flag)
=========================================== 63 passed, 31 skipped in 11.59s ===========================================
Requirement already satisfied: build==0.1.0 from file:///tmp/tmpruiwi01g/build-0.1.0-py2.py3-none-any.whl in ./.tox/py39-wheel/lib/python3.9/site-packages (0.1.0)
Requirement already satisfied: toml in ./.tox/py39-wheel/lib/python3.9/site-packages (from build==0.1.0) (0.10.2)
Requirement already satisfied: pep517>=0.9 in ./.tox/py39-wheel/lib/python3.9/site-packages (from build==0.1.0) (0.9.1)
Requirement already satisfied: packaging in ./.tox/py39-wheel/lib/python3.9/site-packages (from build==0.1.0) (20.4)
Requirement already satisfied: pyparsing>=2.0.2 in ./.tox/py39-wheel/lib/python3.9/site-packages (from packaging->build==0.1.0) (2.4.7)
Requirement already satisfied: six in ./.tox/py39-wheel/lib/python3.9/site-packages (from packaging->build==0.1.0) (1.15.0)
_______________________________________________________ summary _______________________________________________________
  py39-wheel: commands succeeded
  congratulations :)
```

The ultimate culprit appears to be the wheel package (or setuptools, whichever sets the output dir) which generates build artefacts in 'build' in the project root irrespective of the `outdir`.  This can give rise to several different race conditions, e.g. the metadata folder is deleted by another runner before it can be read, which is, presumably, what happened above:

```
[Errno 2] No such file or directory: 'build/bdist.macosx-10.6-x86_64/wheel/build-0.1.0-py3.9.egg-info'
```

And again:

```
ValueError: Egg metadata expected at build/bdist.macosx-10.6-x86_64/wheel/build-0.1.0-py3.9.egg-info but not found
```

No idea why the tests don't crash on other platforms.

**Comment by layday** [comment]
This doesn't really work on a fundamental level; the workers are reinstalling and overwriting `build` in the tox env.  tox needs to be able to create a separate env for every `pytest-xdist` worker, or `build` needs to be installed in a nested env, or `build` needs to be bootstrapped before running `pytest`.

**Comment by gaborbernat** [comment]
xdist forks processes, so they contain and have access to the same python as the host one.

**Comment by layday** [comment]
Yeah, but every forked process will execute `_setup` from `conftest.py` - pytest attempts to build and install `build` at the start of every run.

**Comment by gaborbernat** [comment]
Oh yeah we need some looking around there and run it just once.

**Comment by FFY00** [comment]
We already pull filelock, we can use the approach described in https://github.com/pytest-dev/pytest-xdist#making-session-scoped-fixtures-execute-only-once.

**Comment by layday** [comment]
Fixtures run after test collection so this won't work with `build` being a module-level import unless we install build with tox initially then reinstall it with pytest.

**Comment by FFY00** [comment]
I mean using a lock. The first runner would create the lock and do the setup, the rest would not do anything and just wait for the lock to release.

This is something that we shouldn't be doing in the test suite anyway, the test runner should be the one to setup the environment.

**Comment by layday** [comment]
Well, we'd have to find somewhere to place the lock without access to fixtures.

I agree that installing `build` shouldn't be part of the test suite.  Why are we doing it this way anyway - what do installing the sdist and wheel separately and testing the source tree accomplish?

**Comment by FFY00** [comment]
We can put it where the code is right now. I am unhappy about the code being called on import but that is a parallel issue.

Make sure they all work. These are just sanity checks, to make sure we are producing valid sdists and wheels.

**Comment by layday** [comment]
> We can put it where the code is right now. I am unhappy about the code being called on import but that is a parallel issue.

As in, where would the lock file itself be located.  A temporary folder might have to be created externally from pytest and e.g. exposed as an env var.

> Make sure they all work. These are just sanity checks, to make sure we are producing valid sdists and wheels.

Then perhaps they could be created in a previous step in tox. Something like:

```patch
diff --git a/tox.ini b/tox.ini
index d040ec3..0cca73d 100644
--- a/tox.ini
+++ b/tox.ini
@@ -22,16 +22,15 @@ passenv =
     PYTEST_*
 setenv =
     COVERAGE_FILE = {toxworkdir}/.coverage.{envname}
-    path: TEST_MODE = path
-    sdist: TEST_MODE = sdist
-    wheel: TEST_MODE = wheel
+    path: PYTHONPATH = {toxinidir}/src
     {py27,pypy2}: PYTHONWARNINGS = ignore:DEPRECATION::pip._internal.cli.base_command
-skip_install = false
-deps =
-    path,sdist,wheel: -rrequirements-dev.txt
 extras =
     test
 commands =
+    sdist: python -m build --sdist --outdir {envtmpdir}/dist
+    sdist: pip install --upgrade {envtmpdir}/dist/build-0.1.0.tar.gz
+    wheel: python -m build --wheel --outdir {envtmpdir}/dist
+    wheel: pip install --upgrade {envtmpdir}/dist/build-0.1.0-py2.py3-none-any.whl
     pytest -rsx --cov --cov-config setup.cfg \
       --cov-report=html:{envdir}/htmlcov --cov-context=test \
       --cov-report=xml:{toxworkdir}/coverage.{envname}.xml \
```

**Comment by gaborbernat** [comment]
> Then perhaps they could be created in a previous step in tox. Something like:

I did not want to do this because this would mean you can only run the wheel tox environments from within tox, and not from within an IDE. Translation: if I create an environment within tox entitled ``py39-wheel``, set that environment as my interpreter to use within my IDE running a test should actually run the test via wheel mode. So I'm ``-1`` on moving setup logic that needs to be done at every run into ``tox.ini``...
