### ISSUE TITLE
pipx run --spec build still broken

### ISSUE THREAD

**Issue by henryiii** [pypa/build#228]
I'm still getting the same error as in #226:

```
Run pipx run --spec build==0.2.1 pyproject-build --sdist
Uninstalling setuptools-39.0.1:
  Successfully uninstalled setuptools-39.0.1
25l25h
Usage:   
  /tmp/build-env-5zipwlv4/bin/python -m pip install [options] <requirement specifier> [package-index-options] ...
  /tmp/build-env-5zipwlv4/bin/python -m pip install [options] -r <requirements file> [package-index-options] ...
  /tmp/build-env-5zipwlv4/bin/python -m pip install [options] [-e] <vcs project url> ...
  /tmp/build-env-5zipwlv4/bin/python -m pip install [options] [-e] <local project path> ...
  /tmp/build-env-5zipwlv4/bin/python -m pip install [options] <archive url/path> ...

no such option: --no-warn-script-location
Traceback (most recent call last):
  File "/opt/pipx/.cache/14c4e297c8a7e45/bin/pyproject-build", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/pipx/.cache/14c4e297c8a7e45/lib/python3.6/site-packages/build/__main__.py", line 210, in entrypoint
    main(sys.argv[1:])
  File "/opt/pipx/.cache/14c4e297c8a7e45/lib/python3.6/site-packages/build/__main__.py", line 206, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "/opt/pipx/.cache/14c4e297c8a7e45/lib/python3.6/site-packages/build/__main__.py", line 94, in build_package
    _build_in_isolated_env(builder, outdir, distributions, config_settings)
  File "/opt/pipx/.cache/14c4e297c8a7e45/lib/python3.6/site-packages/build/__main__.py", line 56, in _build_in_isolated_env
    env.install(builder.build_dependencies)
  File "/opt/pipx/.cache/14c4e297c8a7e45/lib/python3.6/site-packages/build/env.py", line 143, in install
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/build-env-5zipwlv4/bin/python', '-Im', 'pip', 'install', '--no-warn-script-location', '-r', '/tmp/build-reqs-pgst_mml.txt']' returned non-zero exit status 2.
```

See here:
https://github.com/scikit-hep/boost-histogram/runs/1868826515?check_suite_focus=true

I can reproduce it locally with these four lines:

```bash
docker run --rm -it ubuntu:18.04
apt-get update && apt-get install -y python3-pip python3-venv
python3 -m pip install pipx
pipx run --spec build pyproject-build
```

**Comment by henryiii** [comment]
Note: `python3 --version` produces `Python 3.6.9` on Ubuntu 18.04.

**Comment by uranusjr** [comment]
I hate Debian.

**Comment by layday** [comment]
What is even going on here?  Did Debian/Ubuntu replace the version of pip from `ensurepip`?

**Comment by uranusjr** [comment]
Yes, the ensurepip module they ship would populate virtual environments with the same pip version as `python-pip`, not the default version bundled in CPython.

**Comment by layday** [comment]
See https://github.com/pypa/packaging-problems/issues/444 where this is even happening on Python 3.8.
