### ISSUE TITLE
Build environment is not isolated when using Apple Python and virtualenv

### ISSUE THREAD

**Issue by Lenderson2** [pypa/build#294]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

macOS 10.15.7

2. What is your Python version?

python --version -> 2.7.16
python3 -- version -> 3.7.3

3. What version of pip do you have?

python -m pip --version 
-> /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named pip

python3 -m pip --version
-> pip 21.1.1 from /Users/leehenderson/Library/Python/3.7/lib/python/site-packages/pip (python 3.7)

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

- I have followed the tutorial exactly up to the point of running "python3 -m build" in the root directory of my project.
- I immediately get an error that ends with 
subprocess.CalledProcessError: Command '['/var/folders/xy/vvr9444d0w75h5837pb5w82w0000gn/T/build-env-jdtxwbzl/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' died with <Signals.SIGABRT: 6>.

Here is the stack trace:
```pytb
Lees-MBP:packaging_tutorial leehenderson$ python3 -m build
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/leehenderson/Library/Python/3.7/lib/python/site-packages/build/__main__.py", line 214, in <module>
    main(sys.argv[1:], 'python -m build')
  File "/Users/leehenderson/Library/Python/3.7/lib/python/site-packages/build/__main__.py", line 206, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "/Users/leehenderson/Library/Python/3.7/lib/python/site-packages/build/__main__.py", line 94, in build_package
    _build_in_isolated_env(builder, outdir, distributions, config_settings)
  File "/Users/leehenderson/Library/Python/3.7/lib/python/site-packages/build/__main__.py", line 52, in _build_in_isolated_env
    with IsolatedEnvBuilder() as env:
  File "/Users/leehenderson/Library/Python/3.7/lib/python/site-packages/build/env.py", line 91, in __enter__
    executable, scripts_dir = _create_isolated_env_venv(self._path)
  File "/Users/leehenderson/Library/Python/3.7/lib/python/site-packages/build/env.py", line 199, in _create_isolated_env_venv
    venv.EnvBuilder(with_pip=True).create(path)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/venv/__init__.py", line 68, in create
    self._setup_pip(context)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/venv/__init__.py", line 261, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/var/folders/xy/vvr9444d0w75h5837pb5w82w0000gn/T/build-env-wxoej6zi/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' died with <Signals.SIGABRT: 6>.
```

I'm new to building packages, so your help would be greatly appreciated! Thank you!

**Comment by henryiii** [comment]
But is this still an unsolved bug with the virtualenv creation?

**Comment by layday** [comment]
This is unrelated to #271 if that's what you mean.

**Comment by Lenderson2** [comment]
@layday thanks for doing the troubleshooting and giving me some solutions. Really appreciate it!

**Comment by layday** [comment]
IIRC, this was fixed ages ago.  Closing for now.
