### ISSUE TITLE
Space in directory name

### ISSUE THREAD

**Issue by henryiii** [pypa/build#325]
When testing out build support in cibuildwheel 2.0.0a4, I run into this failure:

```pytb
python -m build . --wheel --outdir=C:\Users\RUNNER~1\AppData\Local\Temp\cibuildwheelt0jax362\built_wheel --config-setting=-v
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'C:\\Program'
Traceback (most recent call last):
  File "C:\cibw\python\python.3.8.10\tools\lib\site-packages\build\__main__.py", line 302, in main
    build_call(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependency_check)
  File "C:\cibw\python\python.3.8.10\tools\lib\site-packages\build\__main__.py", line 145, in build_package
    _build(isolation, builder, outdir, distribution, config_settings, skip_dependency_check)
  File "C:\cibw\python\python.3.8.10\tools\lib\site-packages\build\__main__.py", line 101, in _build
    return _build_in_isolated_env(builder, outdir, distribution, config_settings)
  File "C:\cibw\python\python.3.8.10\tools\lib\site-packages\build\__main__.py", line 81, in _build_in_isolated_env
    env.install(builder.build_system_requires)
  File "C:\cibw\python\python.3.8.10\tools\lib\site-packages\build\env.py", line 169, in install
    subprocess.check_call(cmd)
  File "C:\cibw\python\python.3.8.10\tools\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\runneradmin\\AppData\\Local\\Temp\\build-env-s3f7jwu0\\Scripts\\python.exe', '-Im', 'pip', 'install', '--use-pep517', '--no-warn-script-location', '-r', 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\build-reqs-ckde1r2k.txt']' returned non-zero exit status 1.

ERROR Command '['C:\\Users\\runneradmin\\AppData\\Local\\Temp\\build-env-s3f7jwu0\\Scripts\\python.exe', '-Im', 'pip', 'install', '--use-pep517', '--no-warn-script-location', '-r', 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\build-reqs-ckde1r2k.txt']' returned non-zero exit status 1.
```

I _think_ this is a problem with quoting paths on Windows probably in `build`, or maybe `pip`? The same build works using `pip wheel` from cibuildwheel.

**Comment by layday** [comment]
Where is the "Program" (presumably "Program Files") path coming from?

**Comment by henryiii** [comment]
I haven't figured that out yet. The error is coming from pip: https://github.com/pypa/pip/blob/7a77484a492c8f1e1f5ef24eaf71a43df9ea47eb/src/pip/_internal/req/req_file.py#L549

**Comment by henryiii** [comment]
`cibuildwheel` installs Python into the "normal" location for macOS and Windows, so that's likely in Program Files. But have no idea why there's a requirement file there. (I'll try to start up a Windows machine later to debug - could also try adding a space into the path that the CI runs in)

**Comment by henryiii** [comment]
Wasn't a to reproduce in the test suite, but I have an idea - if true, it might be pip's fault.

**Comment by henryiii** [comment]
I believe the issue is that `PIP_CONSTRAINTS="path with space.txt"` does not work - it's trying to define separate constraint files instead. This is the in the workaround from #292.

Ideally, build would provide some interface to define constraints that would, for now, be converted to `--constraints` to pip but would be adapted to a new tool if pip was replaced - this workaround is only valid as long as pip is the package installer used.

**Comment by uranusjr** [comment]
Another work around is to use `file://` URLs (for which you can percent-escape the path).

**Comment by layday** [comment]
Why would it not be able to read a path spaces in it? How do you actually call pip?

**Comment by henryiii** [comment]
The environment variable is set to the path. 

https://github.com/pypa/cibuildwheel/blob/ec424751f5c79c42fdbd42634a22768c837fb758/cibuildwheel/windows.py#L315-L331

**Comment by uranusjr** [comment]
I know, what I meant was you can do something like

```python
if options.dependency_constraints:
    constraints_path = options.dependency_constraints.get_for_python_version(config.version)
    build_env["PIP_CONSTRAINT"] = constraints_path.as_uri()
```

I think pip will do the right thing with that.

**Comment by henryiii** [comment]
I was respond to @layday (not sure where his comment is now, don't see it above). Yes, I'm already trying that out in https://github.com/pypa/cibuildwheel/pull/738. I realize another test I can do is turn off constraints in the PR that was failing, https://github.com/scikit-hep/boost-histogram/pull/583, just to be sure that's the root of the issue. Though I think it must be.

**Comment by henryiii** [comment]
Looks like that doesn't work on Windows; pip fumbles over the drive letter. It does fix a path with spaces for macOS.

**Comment by uranusjr** [comment]
Hmm, it shouldn’t fail with that drive letter. Could you file this as a bug?

**Comment by henryiii** [comment]
Will move this to cibuildwheel so we can make sure it's fixed before 2.0.0 final and then open an issue for Pip, which is the actual culprit of the bug :).
