### ISSUE TITLE
build 0.7.0 doesn't like extras_require or entry_points

### ISSUE THREAD

**Issue by tundish** [pypa/build#383]
- Linux 5.4.0-84-generic x86_64 x86_64 x86_64 GNU/Linux
- Python 3.9.5
- pip 21.3
- build 0.7.0
To reproduce, run `<venv>/bin/python -m build .` against [this project's](https://github.com/tundish/balladeer) `setup.py`

Primary error:

> Traceback (most recent call last):
  File ".../py3.9-dev/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File ".../py3.9-dev/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File ".../py3.9-dev/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 297, in get_requires_for_build_sdist
    return hook(config_settings)
  File "/tmp/build-env-avqexshf/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "/tmp/build-env-avqexshf/lib/python3.9/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-avqexshf/lib/python3.9/site-packages/setuptools/build_meta.py", line 258, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/tmp/build-env-avqexshf/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 63
    extras_require={
    ^
 SyntaxError: expression cannot contain assignment, perhaps you meant "=="?

Secondary error:
On removing `extras_require`, there is a subsequent similar error concerning `entry_points`.

**Comment by tundish** [comment]
> I haven't read the article but adding build to your extras is almost certainly not what you want - you are creating a circular dependency between your project and build. You need build to build your project but to install build to build your project you need to have built your project.

That's interesting and was not at all obvious to me. Perhaps there should be some documentation to that effect.
If _build_ allows for pluggable back ends (?) How is it possible to tag that a package requires a particular back end?
