### ISSUE TITLE
build breaks with circular dependencies

### ISSUE THREAD

**Issue by felixonmars** [pypa/build#511]
The latest version of poetry (1.2.0) has a circular dependency on poetry-plugin-export(1.0.6):

https://github.com/python-poetry/poetry/blob/1.2.0/pyproject.toml#L48
https://github.com/python-poetry/poetry-plugin-export/blob/1.0.6/pyproject.toml#L19

This unfortunately breaks `build` for any projects trying to use poetry as build-system:

```
* Getting dependencies for wheel...

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/build/__main__.py", line 370, in main
    built = build_call(
  File "/usr/lib/python3.10/site-packages/build/__main__.py", line 203, in build_package
    out = _build(isolation, builder, outdir, distribution, config_settings, skip_dependency_check)
  File "/usr/lib/python3.10/site-packages/build/__main__.py", line 142, in _build
    return _build_in_current_env(builder, outdir, distribution, config_settings, skip_dependency_check)
  File "/usr/lib/python3.10/site-packages/build/__main__.py", line 122, in _build_in_current_env
    missing = builder.check_dependencies(distribution)
  File "/usr/lib/python3.10/site-packages/build/__init__.py", line 384, in check_dependencies
    return {u for d in dependencies for u in check_dependency(d)}
  File "/usr/lib/python3.10/site-packages/build/__init__.py", line 384, in <setcomp>
    return {u for d in dependencies for u in check_dependency(d)}
  File "/usr/lib/python3.10/site-packages/build/__init__.py", line 201, in check_dependency
    yield from check_dependency(other_req_string, ancestral_req_strings + (req_string,), req.extras)
  File "/usr/lib/python3.10/site-packages/build/__init__.py", line 201, in check_dependency
    yield from check_dependency(other_req_string, ancestral_req_strings + (req_string,), req.extras)
  File "/usr/lib/python3.10/site-packages/build/__init__.py", line 201, in check_dependency
    yield from check_dependency(other_req_string, ancestral_req_strings + (req_string,), req.extras)
  [Previous line repeated 915 more times]
...
RecursionError: maximum recursion depth exceeded
```

**Comment by layday** [comment]
Do you actually intend to use Poetry as a build system? Both `poetry` and `poetry-plugin-export` specify `poetry-core` as their sole build dependency.

**Comment by felixonmars** [comment]
Yes, I actually intend to use `poetry` to build other projects and encountered this. Not all projects have migrated to `poetry-core` yet.

**Comment by layday** [comment]
How can I reproduce this error? I don't know how you are installing poetry without poetry-plugin-export so that you are then able to use it to build poetry-plugin-export.

**Comment by felixonmars** [comment]
I don't know the details, but since both of them only needs poetry-core to build, at least installing wouldn't be a problem? (In Arch we are generally using `python -m build --wheel --no-isolation` to build a wheel, and then use `installer` to install the wheel.)

Once both of them are installed, a simple nearly-empty pyproject.toml could trigger the error:

```
$ cat pyproject.toml
[build-system]
requires = ["poetry"]
$ python -m build -nw
* Getting dependencies for wheel...
running egg_info
writing UNKNOWN.egg-info/PKG-INFO
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
writing top-level names to UNKNOWN.egg-info/top_level.txt
listing git files failed - pretending there aren't any
reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
...
<triggers>
```

**Comment by layday** [comment]
That helps, thanks.

**Comment by layday** [comment]
Thanks for the report, this should be fixed in the next version :)

**Comment by felixonmars** [comment]
That's awesome. Thanks!
