### ISSUE TITLE
Creating wheel fails to log properly when calling `build` from another python process

### ISSUE THREAD

**Issue by scbedd** [pypa/build#540]
I maintain some build automation, and as part of that automation we ascertain whether or not a package will be produced given a set of inputs, etc. Long story short, I need to be able to call `python -m build` from within a python script and redirect the output to a file.

Unfortunately, when building the **wheel** (this does NOT repro when targeting source distribution), I see a bunch of this in the log. One for each attempted `log.info`.

```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Python39\lib\logging\__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
ValueError: underlying buffer has been detached
Call stack:
  File "C:\repo\sdk-for-python\venv\lib\site-packages\pep517\in_process\_in_process.py", line 351, in <module>
    main()
  File "C:\repo\sdk-for-python\venv\lib\site-packages\pep517\in_process\_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "C:\repo\sdk-for-python\venv\lib\site-packages\pep517\in_process\_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "C:\Users\scbedd\AppData\Local\Temp\build-env-7rntyzhp\lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "C:\Users\scbedd\AppData\Local\Temp\build-env-7rntyzhp\lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
    self.run_setup()
  File "C:\Users\scbedd\AppData\Local\Temp\build-env-7rntyzhp\lib\site-packages\setuptools\build_meta.py", line 483, in run_setup
    super(_BuildMetaLegacyBackend,
  File "C:\Users\scbedd\AppData\Local\Temp\build-env-7rntyzhp\lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 36, in <module>
  File "C:\Users\scbedd\AppData\Local\Temp\build-env-7rntyzhp\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\scbedd\AppData\Local\Temp\build-env-7rntyzhp\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Users\scbedd\AppData\Local\Temp\build-env-7rntyzhp\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\scbedd\AppData\Local\Temp\build-env-7rntyzhp\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\scbedd\AppData\Local\Temp\build-env-7rntyzhp\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\Users\scbedd\AppData\Local\Temp\build-env-7rntyzhp\lib\site-packages\setuptools\_distutils\dist.py", line 985, in run_command
    log.info("running %s", command)
Message: 'running %s'
Arguments: ('egg_info',)
```

I want to be clear, the wheel is **still successfully generated**, but the logging stream is somehow getting orphaned. This has to be _some_ interplay of the logging due to the nested python call, but I simply don't see why.

Here is my minimal repro of this behavior. It repro's for any selected python package targeted for build. (at least the ones I've tried!)

```python
from subprocess import run
import sys

def run_logged(*args, prefix="", **kwargs):
    logfile = f"{prefix}_logfile.txt"
    logfile_error = f"{prefix}_error_logfile.txt"

    with open(logfile, "w") as log_output, open(logfile_error, "w") as error_output:
        run(*args, **kwargs, stdout=log_output, stderr=error_output)

if __name__ == "__main__":
   # any valid directory containing a python package that you want to build
   setup_directory_or_file = "<path-to-python-package-root>"
   dist = "<output-folder>"
   run_logged([sys.executable, "-m", "build", "--wheel", "--outdir", dist], prefix="create_wheel", cwd=setup_directory_or_file)
```

I'm totally willing to help patch this as well, but I don't even understand the interaction that's _causing_ this.  If I set _anything_ other than leaving `stdout` or `stderr` left at `None`, this behavior repros.

If I simply capture the output, instead of dealing with a file pointer, I also continue to see the same wonky logger failures: `run(*args, **kwargs, capture_output=True, text=True)` I know I'm causing it with the provided redirection, but I'm not certain that should be an error. 

Additionally, running with `--sdist` does _not_ have the same buffer termination issue. Runs to completion with no complaints.

**Comment by henryiii** [comment]
I believe this is a problem with setuptools, not build. I've been seeing this with the setuptools backend of scikit-build-core, while the native backend works correctly and logs (mostly) correctly. (The logs, when using rich, come out very narrow (80 chars) without detecting the terminal width, but that's the only problem). I _think_ this happens with pip as well. I've been meaning to investigate at some point, but I'm pretty sure it's in setuptools or distutils. IIRC, it only happens on Windows, so I haven't debugged it yet (and the setuptools based scikit-build-core backend is still very experimental).

**Comment by scbedd** [comment]
Well I'm glad that someone else is seeing this behavior! I've dug around this a bit a bit more and think you're absolutely right about the source not being in the `build` package. 

In interests of issue cleanliness, I'm going to go ahead and close this issue. If I can dig up the source of the bug in setuptools, I'll file an issue on their tracker👍. Thanks @henryiii
