### ISSUE TITLE
I am suddenly seeing random broken wheels in my CI

### ISSUE THREAD

**Issue by mxmlnkn** [pypa/build#825]
This [commit](https://github.com/mxmlnkn/ratarmount/commit/a5885aaa587d9e5df51dc702061680f87401dc74) contains some logs of my failed CI.

For some reason, I suddenly get random `twine check` errors. Trying to repair the wheel with `zip -F` yields nothing, but `zip -FF` seems to find something and sometimes works(?) but not always, so it might as well be the ephemerality of this issue. Therefore, my best guess is that this is an issue with `build` or any of its dependencies. I may very well be wrong about this, but I do not know where else to go.

Without `zip -FF`, I saw this randomly:

```python3
Checking dist/ratarmount-0.15.2-py3-none-any.whl: PASSED
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.20/x64/bin/twine", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/twine/__main__.py", line 33, in main
    error = cli.dispatch(sys.argv[1:])
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/twine/cli.py", line 123, in dispatch
    return main(args.args)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/twine/commands/check.py", line 194, in main
    return check(parsed_args.dists, strict=parsed_args.strict)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/twine/commands/check.py", line 140, in check
    warnings, is_ok = _check_file(filename, render_warning_stream)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/twine/commands/check.py", line 84, in _check_file
    package = package_file.PackageFile.from_filename(filename, comment=None)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/twine/package.py", line 98, in from_filename
    meta = DIST_TYPES[dtype](filename)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/pkginfo/sdist.py", line 13, in __init__
    self.extractMetadata()
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/pkginfo/distribution.py", line 126, in extractMetadata
    data = self.read()
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/pkginfo/sdist.py", line 40, in read
    archive, names, read_file = self._get_archive(fqn)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/pkginfo/sdist.py", line 21, in _get_archive
    archive = zipfile.ZipFile(fqn)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/zipfile.py", line 1268, in __init__
    self._RealGetContents()
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/zipfile.py", line 1353, in _RealGetContents
    fp.seek(self.start_dir, 0)
OSError: [Errno 22] Invalid argument
Checking dist/ratarmount-0.15.2.tar.gz: 
```

With `zip -FF`, I see this error instead:

```python3
Checking dist/ratarmount-0.15.2-py3-none-any.whl: PASSED
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.0-rc.3/x64/bin/twine", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.0-rc.3/x64/lib/python3.13/site-packages/twine/__main__.py", line 33, in main
    error = cli.dispatch(sys.argv[1:])
  File "/opt/hostedtoolcache/Python/3.13.0-rc.3/x64/lib/python3.13/site-packages/twine/cli.py", line 123, in dispatch
    return main(args.args)
  File "/opt/hostedtoolcache/Python/3.13.0-rc.3/x64/lib/python3.13/site-packages/twine/commands/check.py", line 194, in main
    return check(parsed_args.dists, strict=parsed_args.strict)
  File "/opt/hostedtoolcache/Python/3.13.0-rc.3/x64/lib/python3.13/site-packages/twine/commands/check.py", line 140, in check
    warnings, is_ok = _check_file(filename, render_warning_stream)
                      ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.0-rc.3/x64/lib/python3.13/site-packages/twine/commands/check.py", line 84, in _check_file
    package = package_file.PackageFile.from_filename(filename, comment=None)
  File "/opt/hostedtoolcache/Python/3.13.0-rc.3/x64/lib/python3.13/site-packages/twine/package.py", line 98, in from_filename
    meta = DIST_TYPES[dtype](filename)
  File "/opt/hostedtoolcache/Python/3.13.0-rc.3/x64/lib/python3.13/site-packages/pkginfo/sdist.py", line 13, in __init__
    self.extractMetadata()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.0-rc.3/x64/lib/python3.13/site-packages/pkginfo/distribution.py", line 126, in extractMetadata
    data = self.read()
  File "/opt/hostedtoolcache/Python/3.13.0-rc.3/x64/lib/python3.13/site-packages/pkginfo/sdist.py", line 40, in read
    archive, names, read_file = self._get_archive(fqn)
                                ~~~~~~~~~~~~~~~~~^^^^^
  File "/opt/hostedtoolcache/Python/3.13.0-rc.3/x64/lib/python3.13/site-packages/pkginfo/sdist.py", line 21, in _get_archive
    archive = zipfile.ZipFile(fqn)
  File "/opt/hostedtoolcache/Python/3.13.0-rc.3/x64/lib/python3.13/zipfile/__init__.py", line 1380, in __init__
    self._RealGetContents()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.0-rc.3/x64/lib/python3.13/zipfile/__init__.py", line 1466, in _RealGetContents
    raise BadZipFile("Bad offset for central directory")
zipfile.BadZipFile: Bad offset for central directory
Checking dist/ratarmount-0.15.2.tar.gz:
##[error]Process completed with exit code 1.
```

**Comment by mxmlnkn** [comment]
It seems I was skimming the log to fast. The **zipfile** error occurs when trying to check the .tar.gz file, not the wheel, which makes even less sense.

**Comment by mxmlnkn** [comment]
I am working around this issue about false ZIP positives by recompressing the tarball:

```bash
tarball=$( find dist -name '*.tar.gz' )
if python3 -c 'import sys, zipfile; sys.exit(0 if zipfile.is_zipfile(sys.argv[1]) else 1)' "$tarball"; then
    gzip -c -d "$tarball" > "$tarball.tar"
    for (( i=9; i>0; --i )); do
        cat "$tarball.tar" | gzip -$i > "$tarball"
        if ! python3 -c 'import sys, zipfile; sys.exit(0 if zipfile.is_zipfile(sys.argv[1]) else 1)' "$tarball"
        then break; fi
    done
fi
```

Maybe something like this would also be worth merging into `build`.

**Comment by layday** [comment]
Twine shouldn't really be attempting to read an sdist as a zip. Please report this to them.
